# Evidencias de Reproduccion Experimental - Lab 02 Part 02

Este notebook esta pensado para generar evidencia visual de la Parte II del laboratorio.

Puedes ejecutarlo celda por celda y tomar capturas de:
- entorno y versiones,
- estructura del proyecto,
- archivos generados,
- metricas finales,
- extractos de JSON y CSV,
- y comandos usados en la reproduccion.

## 1. Preparacion

Esta celda define rutas y helpers para leer los archivos del laboratorio.

In [12]:
from pathlib import Path
import json
import platform
import subprocess
import sys
from importlib.metadata import version

cwd = Path.cwd().resolve()
search_roots = [cwd, *cwd.parents]

PART02 = next(
    (
        path for path in search_roots
        if path.name == 'Part-02' and path.parent.name == 'Lab-02'
    ),
    None,
)

if PART02 is None:
    PART02 = next(
        (
            path / 'laboratorios' / 'Lab-02' / 'Part-02'
            for path in search_roots
            if (path / 'laboratorios' / 'Lab-02' / 'Part-02').exists()
        ),
        None,
    )

if PART02 is None:
    raise FileNotFoundError(
        'No se pudo ubicar la carpeta laboratorios/Lab-02/Part-02 desde el directorio actual.'
    )

ROOT = PART02.parents[2]
EVIDENCIAS = PART02 / 'evidencias'
RESULTADOS = PART02 / 'resultados'
METRICS = RESULTADOS / 'metrics'
MODELS = RESULTADOS / 'models' / 'M2'

def relpath(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)

print('ROOT      :', ROOT)
print('PART02    :', PART02)
print('EVIDENCIAS:', EVIDENCIAS)
print('RESULTADOS:', RESULTADOS)

ROOT      : C:\Users\pc\Documents\proyectos\cib12-aprendizaje-maquina-mineria-datos
PART02    : C:\Users\pc\Documents\proyectos\cib12-aprendizaje-maquina-mineria-datos\laboratorios\Lab-02\Part-02
EVIDENCIAS: C:\Users\pc\Documents\proyectos\cib12-aprendizaje-maquina-mineria-datos\laboratorios\Lab-02\Part-02\evidencias
RESULTADOS: C:\Users\pc\Documents\proyectos\cib12-aprendizaje-maquina-mineria-datos\laboratorios\Lab-02\Part-02\resultados

## 2. Entorno y versiones

Esta salida sirve como evidencia de que se uso un entorno compatible.

In [13]:
print('Python executable:', sys.executable)
print('Python version   :', sys.version)
print('Platform         :', platform.platform())

for package_name, label in [
    ('tensorflow', 'tensorflow'),
    ('numpy', 'numpy'),
    ('pandas', 'pandas'),
    ('scipy', 'scipy'),
    ('scikit-learn', 'scikit-learn'),
]:
    print(f'{label:<17}:', version(package_name))

Python executable: c:\Users\pc\Documents\proyectos\cib12-aprendizaje-maquina-mineria-datos\laboratorios\Lab-02\Part-02\.venv311\Scripts\python.exe
Python version   : 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Platform         : Windows-10-10.0.26200-SP0
tensorflow       : 2.15.1
numpy            : 1.26.4
pandas           : 2.2.3
scipy            : 1.11.4
scikit-learn     : 1.4.2

## 3. Estructura de archivos relevantes

Aqui se muestran los archivos clave que puedes usar como evidencia en capturas.

In [14]:
paths_to_show = [
    PART02 / 'src' / 'prepare_datasets.py',
    PART02 / 'src' / 'train_m2.py',
    PART02 / 'src' / 'evaluate_m2.py',
    EVIDENCIAS / 'comandos-ejecutados.txt',
    EVIDENCIAS / 'metricas-reproduccion.csv',
    MODELS / 'with_empty_values' / 'model.keras',
    MODELS / 'without_empty_values' / 'model.keras',
    MODELS / 'without_empty_values' / 'training_summary.json',
    METRICS / 'm2_with_empty_values_evaluation.json',
    METRICS / 'm2_without_empty_values_evaluation.json',
]

for path in paths_to_show:
    print(f'{relpath(path)} -> {path.exists()}')

laboratorios\Lab-02\Part-02\src\prepare_datasets.py -> True
laboratorios\Lab-02\Part-02\src\train_m2.py -> True
laboratorios\Lab-02\Part-02\src\evaluate_m2.py -> True
laboratorios\Lab-02\Part-02\evidencias\comandos-ejecutados.txt -> True
laboratorios\Lab-02\Part-02\evidencias\metricas-reproduccion.csv -> True
laboratorios\Lab-02\Part-02\resultados\models\M2\with_empty_values\model.keras -> True
laboratorios\Lab-02\Part-02\resultados\models\M2\without_empty_values\model.keras -> True
laboratorios\Lab-02\Part-02\resultados\models\M2\without_empty_values\training_summary.json -> True
laboratorios\Lab-02\Part-02\resultados\metrics\m2_with_empty_values_evaluation.json -> True
laboratorios\Lab-02\Part-02\resultados\metrics\m2_without_empty_values_evaluation.json -> True

## 4. Comandos ejecutados

Esta celda muestra el archivo que resume los comandos principales del pipeline.

In [15]:
commands_file = PART02 / 'evidencias' / 'comandos-ejecutados.txt'
if not commands_file.exists():
    raise FileNotFoundError(f'No se encontro el archivo: {commands_file}')

commands_text = commands_file.read_text(encoding='utf-8')
print(commands_text)

powershell -ExecutionPolicy Bypass -File laboratorios\Lab-02\Part-02\scripts\bootstrap_env.ps1

python laboratorios\Lab-02\Part-02\src\prepare_datasets.py --fingerprint-name lab02_ble_ferrero

python laboratorios\Lab-02\Part-02\src\train_m2.py --fingerprint-name lab02_ble_ferrero --variant with_empty_values
python laboratorios\Lab-02\Part-02\src\evaluate_m2.py --fingerprint-name lab02_ble_ferrero --variant with_empty_values

python laboratorios\Lab-02\Part-02\src\train_m2.py --fingerprint-name lab02_ble_ferrero --variant without_empty_values
python laboratorios\Lab-02\Part-02\src\evaluate_m2.py --fingerprint-name lab02_ble_ferrero --variant without_empty_values

python laboratorios\Lab-02\Part-02\src\train_m2.py --fingerprint-name lab02_ble_ferrero --variant with_empty_values --seed 21 --tag seed21
python laboratorios\Lab-02\Part-02\src\evaluate_m2.py --fingerprint-name lab02_ble_ferrero --variant with_empty_values --tag seed21

## 5. Tabla de metricas de reproduccion

Esta tabla es ideal para una captura porque resume las tres corridas principales.

In [16]:
import pandas as pd

metrics_df = pd.read_csv(EVIDENCIAS / 'metricas-reproduccion.csv')
metrics_df

,escenario,mean_m,median_m,min_m,max_m,samples,epochs,final_loss,final_val_loss,comentario
0,with_empty_values,2.3690,2.1413,0.0743,15.9757,662,60,0.01735,0.03107,Reproduccion base del escenario con valores va...
1,with_empty_values_seed21,2.3169,1.9804,0.1214,16.1974,662,55,0.01737,0.02942,Mejor corrida exploratoria del barrido de semi...
2,without_empty_values,2.0750,1.8430,0.0517,8.1161,486,30,0.00032,0.01743,Escenario mas cercano a los resultados del paper

## 6. Extracto del JSON de evaluacion

Aqui se muestra el contenido del archivo JSON del escenario mas cercano al paper.

In [17]:
eval_json = json.loads((METRICS / 'm2_without_empty_values_evaluation.json').read_text(encoding='utf-8'))
print(json.dumps(eval_json, indent=2, ensure_ascii=False))

{
  "fingerprint_name": "lab02_ble_ferrero",
  "variant": "without_empty_values",
  "distance_stats": {
    "count": 486,
    "min": 0.05172874505266556,
    "q1": 1.0584564208118774,
    "median": 1.8429668563189816,
    "mean": 2.0749761062697067,
    "q3": 2.799822148138705,
    "max": 8.11610742677294
  }
}

## 7. Extracto del resumen de entrenamiento

Esta salida muestra el archivo `training_summary.json` del escenario `without_empty_values`.

In [18]:
training_json = json.loads((MODELS / 'without_empty_values' / 'training_summary.json').read_text(encoding='utf-8'))
print(json.dumps(training_json, indent=2, ensure_ascii=False))

{
  "fingerprint_name": "lab02_ble_ferrero",
  "variant": "without_empty_values",
  "epochs_ran": 30,
  "final_loss": 0.0003169733681716025,
  "final_val_loss": 0.017426563426852226
}

## 8. Comparacion rapida con el paper

Esta celda calcula de forma directa la diferencia entre el paper y la reproduccion.

In [19]:
paper = {
    'with_empty_values': {'mean': 2.0368, 'median': 1.8199},
    'without_empty_values': {'mean': 2.0559, 'median': 1.7745},
}

rows = []
for _, row in metrics_df.iterrows():
    scenario = row['escenario']
    if scenario.startswith('with_empty_values'):
        reference = paper['with_empty_values']
    else:
        reference = paper['without_empty_values']
    rows.append({
        'escenario': scenario,
        'paper_mean': reference['mean'],
        'reproduction_mean': row['mean_m'],
        'delta_mean': round(row['mean_m'] - reference['mean'], 4),
        'paper_median': reference['median'],
        'reproduction_median': row['median_m'],
        'delta_median': round(row['median_m'] - reference['median'], 4),
    })

comparison_df = pd.DataFrame(rows)
comparison_df

,escenario,paper_mean,reproduction_mean,delta_mean,paper_median,reproduction_median,delta_median
0,with_empty_values,2.0368,2.3690,0.3322,1.8199,2.1413,0.3214
1,with_empty_values_seed21,2.0368,2.3169,0.2801,1.8199,1.9804,0.1605
2,without_empty_values,2.0559,2.0750,0.0191,1.7745,1.8430,0.0685

## 9. Muestra de archivos de salida

Esta celda lista modelos, metricas y evidencias disponibles para documentar el laboratorio.

In [20]:
files = []
for folder in [MODELS, METRICS, EVIDENCIAS]:
    for path in sorted(folder.rglob('*')):
        if path.is_file():
            files.append({
                'ruta': relpath(path),
                'tamano_bytes': path.stat().st_size,
            })

files_df = pd.DataFrame(files)
files_df.head(25)

                                                 ruta  tamano_bytes
0   laboratorios\Lab-02\Part-02\resultados\models\...       1804153
1   laboratorios\Lab-02\Part-02\resultados\models\...           406
2   laboratorios\Lab-02\Part-02\resultados\models\...           184
3   laboratorios\Lab-02\Part-02\resultados\models\...       1804153
4   laboratorios\Lab-02\Part-02\resultados\models\...           406
5   laboratorios\Lab-02\Part-02\resultados\models\...           245
6   laboratorios\Lab-02\Part-02\resultados\models\...       1804153
7   laboratorios\Lab-02\Part-02\resultados\models\...           406
8   laboratorios\Lab-02\Part-02\resultados\models\...           249
9   laboratorios\Lab-02\Part-02\resultados\models\...       1804153
10  laboratorios\Lab-02\Part-02\resultados\models\...           406
11  laboratorios\Lab-02\Part-02\resultados\models\...           246
12  laboratorios\Lab-02\Part-02\resultados\models\...       1804153
13  laboratorios\Lab-02\Part-02\resultados\models\...           406
14  laboratorios\Lab-02\Part-02\resultados\models\...           247
15  laboratorios\Lab-02\Part-02\resultados\models\...       1804153
16  laboratorios\Lab-02\Part-02\resultados\models\...           406
17  laboratorios\Lab-02\Part-02\resultados\models\...           249
18  laboratorios\Lab-02\Part-02\resultados\models\...       1802107
19  laboratorios\Lab-02\Part-02\resultados\models\...           406
20  laboratorios\Lab-02\Part-02\resultados\models\...           189
21  laboratorios\Lab-02\Part-02\resultados\metrics...           322
22  laboratorios\Lab-02\Part-02\resultados\metrics...           371
23  laboratorios\Lab-02\Part-02\resultados\metrics...           370
24  laboratorios\Lab-02\Part-02\resultados\metrics...           371

## 10. Ejecucion opcional del pipeline

Si quieres volver a correr partes del proceso desde el notebook, descomenta una de las siguientes lineas.

Recomendacion: usa estas celdas solo si realmente quieres regenerar evidencia, porque entrenamiento y evaluacion pueden tardar.

In [21]:
# subprocess.run([
#     sys.executable,
#     str(PART02 / 'src' / 'prepare_datasets.py'),
#     '--fingerprint-name', 'lab02_ble_ferrero'
# ], check=True)

In [ ]:
# subprocess.run([
#     sys.executable,
#     str(PART02 / 'src' / 'train_m2.py'),
#     '--fingerprint-name', 'lab02_ble_ferrero',
#     '--variant', 'without_empty_values'
# ], check=True)

In [ ]:
# subprocess.run([
#     sys.executable,
#     str(PART02 / 'src' / 'evaluate_m2.py'),
#     '--fingerprint-name', 'lab02_ble_ferrero',
#     '--variant', 'without_empty_values'
# ], check=True)

## 11. Conclusiones para capturas

Si quieres tomar capturas con mas valor para el informe, las mejores celdas suelen ser:
1. entorno y versiones,
2. tabla de metricas,
3. comparacion con el paper,
4. extracto del JSON de evaluacion,
5. listado de archivos generados.